spring.application.name=bankproject
server.port=8092

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/testdb
spring.datasource.username=green
spring.datasource.password=1234

# JWT
jwt.secret=sorkaksdlfgksmfdlfkausrmeodnlgoshfogkrpTdj
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true